#dictionary database mapping scraped from https://www.stonybrook.edu/search/people/
#utilized the beautifulSoup4 framework
#Code for scraping data is not included in this homework as it's not part of the requirement
email_to_addr ={
   "aruna.balasubramanian@stonybrook.edu": "Aruna Balasubramanian",
   "andrew.manos@stonybrook.edu": "Andrew Edward Manos",
   "angel.manguera@stonybrook.edu": "Angel A. Manguera",
   "angelita.manguera@stonybrook.edu": "Angelita S. Manguera",
   "anthony.mancuso@stonybrook.edu": "Anthony  Mancuso",
   "august.manfredi@stonybrook.edu": "August J. Manfredi",
   "augustus.mantia@stonybrook.edu": "Augustus G. Mantia",
   "catherine.mancusi@stonybrook.edu": "Catherine  Mancusi",
   "charles.mann@stonybrook.edu": "Charles  Mann",
   "christine.manello@stonybrook.edu": "Christine A. Manello",
   "criselda.manalo@stonybrook.edu": "Criselda S. Manalo",
   "deborah.mann@stonybrook.edu": "Deborah  Mann",
   "diana.mancini@stonybrook.edu": "Diana L Mancini",
   "dominic.mannino@stonybrook.edu": "Dominic M. Mannino",
   "donna.manzi@stonybrook.edu": "Donna M. Manzi",
   "edward.mann@stonybrook.edu": "Edward William Mann",
   "eileen.mann@stonybrook.edu": "Eileen  Mann",
   "elvia.manrique@stonybrook.edu": "Elvia E. Manrique",
   "gail.mandel@stonybrook.edu": "Gail  Mandel",
   "iona.man-cheong@stonybrook.edu": "Iona D. Man-Cheong",
   "jahan.manjur@stonybrook.edu": "Jahan E Manjur",
   "john.mancino@stonybrook.edu": "John M. Mancino",
   "john.manzella@stonybrook.edu": "John Marco Manzella",
   "judith.manzo@stonybrook.edu": "Judith  Manzo",
   "julie.menard@stonybrook.edu": "Julie L. Mangan",
   "koumudi.manthani@stonybrook.edu": "Koumudi  Manthani",
   "louis.mancuso@stonybrook.edu": "Louis  Mancuso",
   "louis.manganas@stonybrook.edu": "Louis  Manganas",
   "man.lu@stonybrook.edu": "Man  Lu",
   "man.lee@stonybrook.edu": "Man P. Lee",
   "manal.soliman@stonybrook.edu": "Manal S. Soliman",
   "mandeep.kaur.1@stonybrook.edu": "Mandeep  Kaur",
   "mandeep.patel@stonybrook.edu": "Mandeep Kaur Patel",
   "mandy.frantz@stonybrook.edu": "Mandy  Frantz",
   "mandy.gillam@stonybrook.edu": "Mandy  Gillam",
   "mandy.lee@stonybrook.edu": "Mandy Mun-Sie Lee",
   "manfred.bocker@stonybrook.edu": "Manfred  Bocker",
   "manishkumar.thakur@stonybrook.edu": "Manish Kumar Thakur",
   "manju.sam@stonybrook.edu": "Manju B. Sam",
   "manmeet.ahluwalia@stonybrook.edu": "Manmeet  Ahluwalia",
   "manognya.koduganti@stonybrook.edu": "Manognya  Koduganti",
   "manouche.sylvain@stonybrook.edu": "Manouche  Sylvain",
   "barbara.walker@stonybrook.edu": "Barbara  Walker",
   "benjamin.walcott@stonybrook.edu": "Benjamin  Walcott",
   "bridget.walsh@stonybrook.edu": "Bridget Colgan Walsh",
   "camille.waldron@stonybrook.edu": "Camille  Waldron",
   "cheryl.young@stonybrook.edu": "Cheryl L Walker",
   "colleen.walsh@stonybrook.edu": "Colleen M. Walsh",
   "david.wallach@stonybrook.edu": "David  Wallach",
   "donna.walker@stonybrook.edu": "Donna L. Walker",
   "eddie.walker@stonybrook.edu": "Eddie  Walker",
   "emma.waltonhamilton@stonybrook.edu": "Emma K. Walton Hamilton",
   "erica.gega@stonybrook.edu": "Erica G. Walker",
   "frederick.walter@stonybrook.edu": "Frederick M. Walter",
   "greta.walker-ametewee@stonybrook.edu": "Greta Y Walker-Ametewee",
   "h.waldman@stonybrook.edu": "H. B. Waldman",
   "harry.p.walsh@stonybrook.edu": "Harry  Walsh",
   "john.walsh.3@stonybrook.edu": "John  Walsh",
   "john.waldron@stonybrook.edu": "John K Waldron",
   "karen.wallin@stonybrook.edu": "Karen E Wallin",
   "kerry.gallagher@stonybrook.edu": "Kerry A. Walsh",
   "kristina.walker@stonybrook.edu": "Kristina M. Walker",
   "laurie.dmuchowski@stonybrook.edu": "Laurie A. Wallace",
   "lindsi.walker@stonybrook.edu": "Lindsi E. C. Walker",
   "lori.walsh@stonybrook.edu": "Lori A. Walsh",
   "louann.walker@stonybrook.edu": "Lou Ann  Walker",
   "martin.wallace@stonybrook.edu": "Martin W. Wallace",
   "mary.walsh@stonybrook.edu": "Mary  Walsh",
   "mary.walton@stonybrook.edu": "Mary  Walton",
   "marylou.walsh@stonybrook.edu": "Mary Lou  Walsh",
   "patricia.m.walsh@stonybrook.edu": "Patricia M Walsh",
   "paula.walker@stonybrook.edu": "Paula M Walker",
   "phyllis.walsh@stonybrook.edu": "Phyllis  Walsh",
   "richard.walsh@stonybrook.edu": "Richard  Walsh",
   "richard.walter@stonybrook.edu": "Richard J Walter",
   "robert.h.walker@stonybrook.edu": "Robert H Walker",
   "rosalind.walcott@stonybrook.edu": "Rosalind  Walcott",
   "ryan.walter@stonybrook.edu": "Ryan  Walter",
   "shahidah.walcott@stonybrook.edu": "Shahidah  Walcott",
   "stephen.walker@stonybrook.edu": "Stephen  Walker",
   "susan.walker@stonybrook.edu": "Susan Diana Walker",
   "susanne.walsh@stonybrook.edu": "Susanne  Walsh",
   "theresa.wallace@stonybrook.edu": "Theresa G. Wallace",
   "tracey.walters@stonybrook.edu": "Tracey L. Walters",
   "waldemar.nieweglowski@stonybrook.edu": "Waldemar  Nieweglowski",
   "waldemar.pacholik@stonybrook.edu": "Waldemar  Pacholik",
   "ying.gu@stonybrook.edu": "Ying  Gu",
   "ying.liu.1@stonybrook.edu": "Ying  Liu",
   "ying.qian@stonybrook.edu": "Ying  Qian",
   "ying.wang@stonybrook.edu": "Ying  Wang",
   "yinghong.xu@stonybrook.edu": "Yinghong  Xu",
   "yingtian.pan@stonybrook.edu": "Yingtian  Pan",
   "yingwu.wang@stonybrook.edu": "Yingwu  Wang",
   "dorothy.neilsen@stonybrook.edu": "Dorothy M. Neilsen",
   "neil.klatsky@stonybrook.edu": "Neil  Klatsky",
   "neil.mendoza@stonybrook.edu": "Neil A Mendoza",
   "neil.dasgupta@stonybrook.edu": "Neil Kumar Dasgupta",
   "neil.werner@stonybrook.edu": "Neil L Werner",
   "neil.monte@stonybrook.edu": "Neil S Monte",
   "neil.farrell@stonybrook.edu": "Neil T Farrell",
   "neill.clenaghan@stonybrook.edu": "Neill  Clenaghan",
   "sally.neilson@stonybrook.edu": "Sally A. Neilson",
   "ying.zhang.3@stonybrook.edu" : "Ying Zhang"
}

#return the name corresponding to an email address, Null if it doesnt exist
def map(email):
   if(email in email_to_addr.keys()):
      return email_to_addr.get(email)
   else:
      return "Null"